# End-to-End NLP: News Headline Classifier (SageMaker Version)

This notebook trains a PyTorch-based model to classify news headlines between four domains: Business (b), Entertainment (e), Health & Medicine (m) and Science & Technology (t).

Following on from the previous local-mode notebook, we show how to trigger the model training and deployment on separate infrastructure - to make better use of resources.


**Install necessary libraries that may not be part of the kernel**

In [60]:
!pip install torchtext  # Depending on your PyTorch version https://pypi.org/project/torchtext/

You should consider upgrading via the '/home/ec2-user/anaconda3/envs/pytorch_latest_p36/bin/python -m pip install --upgrade pip' command.


### Set Up Execution Role and Session

Let's start by specifying:

- The S3 bucket and prefix that you want to use for training and model data. This should be within the same region as the Notebook Instance, training, and hosting. If you don't specify a bucket, SageMaker SDK will create a default bucket following a pre-defined naming convention in the same region. 
- The IAM role ARN used to give SageMaker access to your data. It can be fetched using the **get_execution_role** method from sagemaker python SDK.

In [61]:
%%time
%load_ext autoreload
%autoreload 2

import sagemaker
from sagemaker import get_execution_role

role = get_execution_role()
print(role)
sess = sagemaker.Session()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
arn:aws:iam::344028372807:role/service-role/AmazonSageMaker-ExecutionRole-20190212T154595
CPU times: user 105 ms, sys: 20.7 ms, total: 126 ms
Wall time: 2.16 s


### Download News Aggregator Dataset

The News Aggregator Dataset is available at the public **UCI Machine Learning Database** repository (these files should already be downloaded in previous notebook)


In [62]:
import util.preprocessing

util.preprocessing.download_dataset()

Saved to data/ folder


### Let's visualize the dataset

We will load the newsCorpora.csv file to a Pandas dataframe for our data processing work

In [63]:
import os
import re
import numpy as np
import pandas as pd

In [64]:
column_names = ["TITLE", "URL", "PUBLISHER", "CATEGORY", "STORY", "HOSTNAME", "TIMESTAMP"]
df = pd.read_csv("data/newsCorpora.csv", names=column_names, header=None, delimiter="\t")
df.head()

TITLE  \
1  Fed official says weak data caused by weather,...   
2  Fed's Charles Plosser sees high bar for change...   
3  US open: Stocks fall after Fed official hints ...   
4  Fed risks falling 'behind the curve', Charles ...   
5  Fed's Plosser: Nasty Weather Has Curbed Job Gr...   

                                                 URL          PUBLISHER  \
1  http://www.latimes.com/business/money/la-fi-mo...  Los Angeles Times   
2  http://www.livemint.com/Politics/H2EvwJSK2VE6O...           Livemint   
3  http://www.ifamagazine.com/news/us-open-stocks...       IFA Magazine   
4  http://www.ifamagazine.com/news/fed-risks-fall...       IFA Magazine   
5  http://www.moneynews.com/Economy/federal-reser...          Moneynews   

  CATEGORY                          STORY             HOSTNAME      TIMESTAMP  
1        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM      www.latimes.com  1394470370698  
2        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM     www.livemint.com  1394470371207  
3        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM  www.ifamagazine.com  1394470371550  
4        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM  www.ifamagazine.com  1394470371793  
5        b  ddUyU0VZz0BRneMioxUPQVP6sIxvM    www.moneynews.com  1394470372027

For this exercise we'll **only use**:

- The **title** (Headline) of the news story, as our input
- The **category**, as our target variable


In [65]:
df["CATEGORY"].value_counts()

e    152469
b    115967
t    108344
m     45639
Name: CATEGORY, dtype: int64

The dataset has four article categories: Business (b), Entertainment (e), Health & Medicine (m) and Science & Technology (t).


## Natural Language Pre-Processing

We'll do some basic processing of the text data to convert it into numerical form that the algorithm will be able to consume to create a model.

We will do typical pre processing for NLP workloads such as: dummy encoding the labels, tokenizing the documents and set fixed sequence lengths for input feature dimension, padding documents to have fixed length input vectors.


### Dummy Encode the Labels


In [69]:
encoded_y, labels = util.preprocessing.dummy_encode_labels(df, "CATEGORY")
print(labels)
print(encoded_y)

['b' 'e' 'm' 't']
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [70]:
df["CATEGORY"][1231]

't'

In [71]:
encoded_y[0]

array([1., 0., 0., 0.], dtype=float32)

### Tokenize and Set Fixed Sequence Lengths

We want to describe our inputs at the more meaningful word level (rather than individual characters), and ensure a fixed length of the input feature dimension.


In [89]:
import util.preprocessing
processed_docs, tokenizer = util.preprocessing.tokenize_and_pad_docs(df, "TITLE")

72547
defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x7fa06fa0acc0>>, {'<unk>': 0, '<pad>': 1, "'": 2, '.': 3, 'to': 4, ',': 5, 'the': 6, 'in': 7, 's': 8, 'of': 9, 'for': 10, 'on': 11, 'and': 12, 'a': 13, 'with': 14, 'new': 15, 'at': 16, 'is': 17, '?': 18, 'as': 19, 'us': 20, 'from': 21, '(': 22, ')': 23, 'after': 24, 'google': 25, 'by': 26, 'up': 27, 'be': 28, 'apple': 29, '-': 30, '2014': 31, 'will': 32, 'says': 33, '!': 34, 'it': 35, 'over': 36, 'video': 37, 'more': 38, 'samsung': 39, 'first': 40, 'you': 41, 'may': 42, '2': 43, 't': 44, 'not': 45, 'microsoft': 46, 'about': 47, 'galaxy': 48, 'facebook': 49, 'one': 50, 'out': 51, '&': 52, 'report': 53, 'are': 54, '4': 55, 'watch': 56, 'kardashian': 57, 'kim': 58, 'this': 59, 'season': 60, 'star': 61, 'your': 62, 'china': 63, 'game': 64, 'review': 65, 'day': 66, 'what': 67, 'how': 68, 'million': 69, 'has': 70, 'but': 71, 'sales': 72, 'amazon': 73, 'that': 74, 'could': 75, 'its': 76, 'deal': 77, 

In [90]:
df["TITLE"][1]

'Fed official says weak data caused by weather, should not slow taper'

In [91]:
processed_docs[0]

array([ 184,  469,   33, 1070,   95, 2005,   26, 1113,    5,  273,   45,
       1377, 7665,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    1,    1,    1])

### Import Word Embeddings

To represent our words in numeric form, we'll use pre-trained vector representations for each word in the vocabulary: In this case we'll be using pre-built GloVe word embeddings.

You could also explore training custom, domain-specific word embeddings using SageMaker's built-in [BlazingText algorithm](https://docs.aws.amazon.com/sagemaker/latest/dg/blazingtext.html). See the official [blazingtext_word2vec_text8 sample](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/introduction_to_amazon_algorithms/blazingtext_word2vec_text8) for an example notebook showing how.


In [92]:
embedding_matrix = util.preprocessing.get_word_embeddings(tokenizer, "data/embeddings")


Using existing embeddings file
Loading into memory...
Loaded 400000 word vectors.


In [93]:
np.save(
    file="./data/embeddings/docs-embedding-matrix",
    arr=embedding_matrix,
    allow_pickle=False,
)
vocab_size=embedding_matrix.shape[0]
print(embedding_matrix.shape)


(400000, 100)


### Split Train and Test Sets

Finally we need to divide our data into model training and evaluation sets:


In [98]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    processed_docs,
    encoded_y,
    test_size=0.2,
    random_state=42
)


In [99]:
os.makedirs("./data/train", exist_ok=True)
np.save("./data/train/train_X.npy", X_train)
np.save("./data/train/train_Y.npy", y_train)
os.makedirs("./data/test", exist_ok=True)
np.save("./data/test/test_X.npy", X_test)
np.save("./data/test/test_Y.npy", y_test)


## Upload Data to S3

We'll need to upload our processed data to S3 to make it available for SageMaker training jobs:


In [100]:
s3_bucket = sess.default_bucket()
s3_prefix = "news"


In [101]:
traindata_s3_prefix = f"{s3_prefix}/data/train"
testdata_s3_prefix = f"{s3_prefix}/data/test"
embeddings_s3_prefix = f"{s3_prefix}/data/embeddings"
output_s3 = f"s3://{s3_bucket}/{s3_prefix}/models/"


In [102]:
train_s3 = sess.upload_data(path="./data/train/", bucket=s3_bucket, key_prefix=traindata_s3_prefix)
test_s3 = sess.upload_data(path="./data/test/", bucket=s3_bucket, key_prefix=testdata_s3_prefix)
embeddings_s3 = sess.upload_data(
    # Only send the numpy array of embeddings, not the original files as well:
    path="./data/embeddings/docs-embedding-matrix.npy",
    bucket=s3_bucket,
    key_prefix=embeddings_s3_prefix,
)


In [148]:
# Use below for local mode
#working_dir = os.getcwd()
#inputs = {"train": "file://{}/data/train/".format(working_dir), 
#         "test": "file://{}/data/test/".format(working_dir), 
#          "embeddings": "file://{}/data/embeddings/".format(working_dir)}

inputs = { "train": train_s3, "test": test_s3, "embeddings": embeddings_s3 }
print(inputs)

{'train': 'file:///home/ec2-user/SageMaker/sagemaker-workshop-101/pytorch_alternatives/custom_pytorch_nlp/data/train/', 'test': 'file:///home/ec2-user/SageMaker/sagemaker-workshop-101/pytorch_alternatives/custom_pytorch_nlp/data/test/', 'embeddings': 'file:///home/ec2-user/SageMaker/sagemaker-workshop-101/pytorch_alternatives/custom_pytorch_nlp/data/embeddings/'}


## Train with Differentiated Infrastructure on Sagemaker

This time, we've packaged the model build and train code in the [**main.py**](src/main.py) script in the **src** directory.

We'll use the high-level PyTorch SDK to train our model on SageMaker.

You can explore the script file for more details on the interface.


### How Amazon SageMaker runs your PyTorch script with pre-built containers

Amazon Sagemaker has pre packaged a set of Docker images to help you accelerate building your projects. This what is driving the Sagemaker PyTorch Estimator. You can use the same PyTorch image for training and/or hosting. You can find more information in the following: https://github.com/aws/sagemaker-pytorch-training-toolkit , https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html, https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html


#### Running your container during training

When Amazon SageMaker runs training, your training script (entry_point input) is run just like a regular Python program. A number of files are laid out for your use, under a `/opt/ml` directory. These will be locations that you can access from within your script. You will see an example of the use of this in our [**main.py**](src/main.py) :

    /opt/ml
    |-- code
    |   `-- <our script(s)>
    |-- input
    |   |-- config
    |   |   |-- hyperparameters.json
    |   |   `-- resourceConfig.json
    |   `-- data
    |       `-- <channel_name>
    |           `-- <input data>
    |-- model
    |   `-- <model files>
    `-- output
        `-- failure

##### The input

* `/opt/ml/input/config` contains information to control how your program runs. `hyperparameters.json` is a JSON-formatted dictionary of hyperparameter names to values. These values will always be strings, so you may need to convert them. `resourceConfig.json` is a JSON-formatted file that describes the network layout used for distributed training. Since scikit-learn doesn't support distributed training, we'll ignore it here.
* `/opt/ml/input/data/<channel_name>/` (for File mode) contains the input data for that channel. The channels are created based on the call to CreateTrainingJob but it's generally important that channels match what the algorithm expects. The files for each channel will be copied from S3 to this directory, preserving the tree structure indicated by the S3 key structure. 
* `/opt/ml/input/data/<channel_name>_<epoch_number>` (for Pipe mode) is the pipe for a given epoch. Epochs start at zero and go up by one each time you read them. There is no limit to the number of epochs that you can run, but you must close each pipe before reading the next epoch.

##### The output

* `/opt/ml/model/` is the directory where you write the model that your algorithm generates. Your model can be in any format that you want. It can be a single file or a whole directory tree. SageMaker will package any files in this directory into a compressed tar archive file. This file will be available at the S3 location returned in the `DescribeTrainingJob` result.
* `/opt/ml/output` is a directory where the algorithm can write a file `failure` that describes why the job failed. The contents of this file will be returned in the `FailureReason` field of the `DescribeTrainingJob` result. For jobs that succeed, there is no reason to write this file as it will be ignored.


In [149]:
import sagemaker
from sagemaker.pytorch.estimator import PyTorch as PyTorchEstimator

Although the script will run on a separate container, we can pass whatever parameters it needs through SageMaker:


In [150]:
hyperparameters = { "epochs": 5, "vocab_size": vocab_size, "num_classes": 4 }

algo-1-v2asl_1  | 2020-12-05 14:31:52,775 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178712
algo-1-v2asl_1  | 2020-12-05 14:31:52,775 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:11.203746795654297|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178712
algo-1-v2asl_1  | 2020-12-05 14:31:52,775 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:96.8477554321289|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178712
algo-1-v2asl_1  | 2020-12-05 14:31:52,775 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:89.6|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178712
algo-1-v2asl_1  | 2020-12-05 14:31:52,775 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:338384.37890625|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178712
algo-1-v2asl_1  | 2020-12-05 14:31:52,775 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:37839.90625|#Level:Host|#hostname:ec9359f32c34,

We have our `TensorFlow` estimator object, we have set the hyper-parameters for this object and we have our data channels linked with the algorithm. The only  remaining thing to do is to train the algorithm. The following command will train the algorithm. Training the algorithm involves a few steps. Firstly, the instance that we requested while creating the `TensorFlow` estimator classes is provisioned and is setup with the appropriate libraries. Then, the data from our channels are downloaded into the instance. Once this is done, the training job begins. The provisioning and data downloading will take some time, depending on the size of the data. 

Once the job has finished a "Job complete" message will be printed. The trained model can be found in the S3 bucket that was setup as `output_path` in the estimator.

We will run the training job using a ml.p3.2xlarge instance (GPUs) to accelerate our training. If your account runs into resource limits please use a ml.c5.xlarge instance. 

In [151]:
estimator = PyTorchEstimator(
    framework_version="1.6.0",
    py_version="py3",
    instance_count=1,
    instance_type="ml.p3.2xlarge",
    role=role,
    entry_point="main.py",
    source_dir="./src",
    hyperparameters=hyperparameters,
    metric_definitions=[
        { "Name": "Epoch", "Regex": "epoch: ([0-9\\.]+)" },
        { "Name": "Train:Loss", "Regex": "train_loss: ([0-9\\.]+)" },
        { "Name": "Validation:Loss", "Regex": "val_loss: ([0-9\\.]+)" },
        { "Name": "Validation:Accuracy", "Regex": "val_acc: ([0-9\\.]+)" },
    ],
    base_job_name="news-pytorch",
    max_run=20*60,  # Maximum allowed active runtime
    use_spot_instances=True,  # Use spot instances to reduce cost
    max_wait=30*60,  # Maximum clock time (including spot delays)
)

estimator.fit(inputs)


Creating tmpinr_co8r_algo-1-jhajk_1 ... 
Attaching to tmpinr_co8r_algo-1-jhajk_12mdone
algo-1-jhajk_1  | 2020-12-05 14:32:04,078 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training
algo-1-jhajk_1  | 2020-12-05 14:32:04,081 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
algo-1-jhajk_1  | 2020-12-05 14:32:04,089 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
algo-1-jhajk_1  | 2020-12-05 14:32:04,092 sagemaker_pytorch_container.training INFO     Invoking user training script.
algo-1-jhajk_1  | 2020-12-05 14:32:05,250 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
algo-1-jhajk_1  | 2020-12-05 14:32:05,262 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
algo-1-jhajk_1  | 2020-12-05 14:32:05,274 sagemaker-training-toolkit INFO     No GPUs detected (normal if no gpus installed)
algo-1-jhajk_1  | 2020-12-05 1

algo-1-v2asl_1  | 2020-12-05 14:33:52,774 [INFO ] pool-2-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178832
algo-1-v2asl_1  | 2020-12-05 14:33:52,774 [INFO ] pool-2-thread-1 TS_METRICS - DiskAvailable.Gigabytes:11.203258514404297|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178832
algo-1-v2asl_1  | 2020-12-05 14:33:52,774 [INFO ] pool-2-thread-1 TS_METRICS - DiskUsage.Gigabytes:96.8482437133789|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178832
algo-1-v2asl_1  | 2020-12-05 14:33:52,774 [INFO ] pool-2-thread-1 TS_METRICS - DiskUtilization.Percent:89.6|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178832
algo-1-v2asl_1  | 2020-12-05 14:33:52,774 [INFO ] pool-2-thread-1 TS_METRICS - MemoryAvailable.Megabytes:337537.2109375|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178832
algo-1-v2asl_1  | 2020-12-05 14:33:52,774 [INFO ] pool-2-thread-1 TS_METRICS - MemoryUsed.Megabytes:38687.34375|#Level:Host|#hostname:ec9359f32c34,t

algo-1-v2asl_1  | 2020-12-05 14:38:15,432 [INFO ] W-9051-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9051-model_1-stdout
algo-1-v2asl_1  | 2020-12-05 14:38:15,433 [INFO ] W-9093-model_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9093-model_1-stderr
algo-1-v2asl_1  | 2020-12-05 14:38:15,433 [INFO ] W-9028-model_1-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9028-model_1-stderr
algo-1-v2asl_1  | 2020-12-05 14:38:15,433 [INFO ] W-9093-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9093-model_1-stdout
algo-1-v2asl_1  | 2020-12-05 14:38:15,433 [INFO ] W-9028-model_1-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9028-model_1-stdout
algo-1-v2asl_1  | 2020-12-05 14:38:15,433 [INFO ] epollEventLoopGroup-5-83 org.pytorch.serve.wlm.WorkerThread - 9041 Worker disconnected. WORKER_MODEL_LOADED
algo-1-v2asl_1  | 2020-12-05 14:38:15,433 [INFO ] epollEventLoopGroup-5-61 org.pyt

tmpk6ffw7ty_algo-1-v2asl_1 exited with code 1
Aborting on container exit...


Exception in thread Thread-12:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 627, in run
    _stream_output(self.process)
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 687, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 632, in run
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpk6ffw7ty/docker-compose.yaml', 'up', '--build', '--abort-on-contain

## Use the Model: Hosting / Inference
Once the training is done, we can deploy the trained model as an Amazon SageMaker real-time hosted endpoint. This will allow us to make predictions (or inference) from the model. Note that we don't have to host on the same type of instance that we used to train. Because instance endpoints will be up and running for long, it's advisable to choose a cheaper instance for inference.


In [143]:
predictor = estimator.deploy(
    initial_instance_count=1,
    instance_type="ml.t2.medium",
)

Attaching to tmpk6ffw7ty_algo-1-v2asl_1
algo-1-v2asl_1  | ['torchserve', '--start', '--model-store', '/.sagemaker/ts/models', '--ts-config', '/etc/sagemaker-ts.properties', '--log-config', '/opt/conda/lib/python3.6/site-packages/sagemaker_pytorch_serving_container/etc/log4j.properties', '--models', 'model.mar']
algo-1-v2asl_1  | 2020-12-05 14:25:51,575 [INFO ] main org.pytorch.serve.ModelServer - 
algo-1-v2asl_1  | Torchserve version: 0.2.1
algo-1-v2asl_1  | TS Home: /opt/conda/lib/python3.6/site-packages
algo-1-v2asl_1  | Current directory: /
algo-1-v2asl_1  | Temp directory: /home/model-server/tmp
algo-1-v2asl_1  | Number of GPUs: 0
algo-1-v2asl_1  | Number of CPUs: 96
algo-1-v2asl_1  | Max heap size: 30688 M
algo-1-v2asl_1  | Python executable: /opt/conda/bin/python
algo-1-v2asl_1  | Config file: /etc/sagemaker-ts.properties
algo-1-v2asl_1  | Inference address: http://0.0.0.0:8080
algo-1-v2asl_1  | Management address: http://0.0.0.0:8080
algo-1-v2asl_1  | Metrics address: http://127

algo-1-v2asl_1  | 2020-12-05 14:25:54,885 [INFO ] W-9093-model_1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 1693
algo-1-v2asl_1  | 2020-12-05 14:25:54,886 [INFO ] W-9093-model_1 TS_METRICS - W-9093-model_1.ms:2479|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178354
algo-1-v2asl_1  | 2020-12-05 14:25:54,957 [INFO ] W-9084-model_1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 1764
algo-1-v2asl_1  | 2020-12-05 14:25:54,958 [INFO ] W-9084-model_1 TS_METRICS - W-9084-model_1.ms:2592|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178354
algo-1-v2asl_1  | 2020-12-05 14:25:54,967 [INFO ] W-9074-model_1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 1774
algo-1-v2asl_1  | 2020-12-05 14:25:54,967 [INFO ] W-9074-model_1 TS_METRICS - W-9074-model_1.ms:2628|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178354
algo-1-v2asl_1  | 2020-12-05 14:25:54,984 [INFO ] W-9033-model_1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 1577
algo-1-v2

algo-1-v2asl_1  | 2020-12-05 14:25:55,297 [INFO ] W-9082-model_1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 1823
algo-1-v2asl_1  | 2020-12-05 14:25:55,297 [INFO ] W-9082-model_1 TS_METRICS - W-9082-model_1.ms:2931|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178355
algo-1-v2asl_1  | 2020-12-05 14:25:55,302 [INFO ] W-9035-model_1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 1659
algo-1-v2asl_1  | 2020-12-05 14:25:55,302 [INFO ] W-9035-model_1 TS_METRICS - W-9035-model_1.ms:3021|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178355
algo-1-v2asl_1  | 2020-12-05 14:25:55,302 [INFO ] W-9011-model_1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 1903
algo-1-v2asl_1  | 2020-12-05 14:25:55,302 [INFO ] W-9011-model_1 TS_METRICS - W-9011-model_1.ms:3030|#Level:Host|#hostname:ec9359f32c34,timestamp:1607178355
algo-1-v2asl_1  | 2020-12-05 14:25:55,310 [INFO ] W-9023-model_1 org.pytorch.serve.wlm.WorkerThread - Backend response time: 1904
algo-1-v2

algo-1-v2asl_1  | 2020-12-05 14:25:57,078 [INFO ] pool-1-thread-97 ACCESS_LOG - /172.18.0.1:37766 "GET /ping HTTP/1.1" 200 8
algo-1-v2asl_1  | 2020-12-05 14:25:57,080 [INFO ] pool-1-thread-97 TS_METRICS - Requests2XX.Count:1|#Level:Host|#hostname:ec9359f32c34,timestamp:null
!

### (**JupyterLab Only**) Installing IPyWidgets Extension

This notebook uses a fun little interactive widget to query the classifier, so **ONLY if you're using JupyterLab** (no action needed for plain Jupyter users) you'll need to install an extension to enable it:

- Select "*Settings > Enable Extension Manager (experimental)*" from the toolbar, and confirm to enable it
- Click on the new jigsaw puzzle piece icon in the sidebar, to open the Extension Manager
- Search for `@jupyter-widgets/jupyterlab-manager` (Scroll down - search results show up *below* the list of currently installed widgets!)
- Click "**Install**" below the widget's description
- Wait for the blue progress bar that appears by the search box
- You should be prompted "*A build is needed to include the latest changes*" - select "**Rebuild**"
- The progress bar should resume, and you should shortly see a "Build Complete" dialogue.
- Select "**Reload**" to reload the webpage


### Your model should now be in production as a RESTful API!

Let's evaluate our model with some example headlines...

If you struggle with the widget, you can always simply call the `classify()` function from Python.

You can be creative with your headlines!


In [145]:
from IPython import display
import ipywidgets as widgets
import torch
#from keras.preprocessing.sequence import pad_sequences

def classify(text):
    """Classify a headline and print the results"""
    processed = tokenizer.preprocess(text)
    padded = tokenizer.pad([processed])
    final_text = []
    for w in padded[0]:
        final_text.append(tokenizer.vocab.stoi[w])
    x = torch.randn(1,1,40)
    result = predictor.predict([final_text])
    print(result)
    ix = np.argmax(result)
    print(f"Predicted class: '{labels[ix]}' with confidence {result[0][ix]:.2%}")

interaction = widgets.interact_manual(
    classify,
    text=widgets.Text(
        value="The markets were bullish after news of the merger",
        placeholder="Type a news headline...",
        description="Headline:",
        layout=widgets.Layout(width="99%"),
    )
)
interaction.widget.children[1].description = "Classify!"


interactive(children=(Text(value='The markets were bullish after news of the merger', description='Headline:',…

## Clean up

Unlike training jobs (which destroy their resources as soon as training is finished), real-time endpoint deployments provision instances until we specifically shut the endpoint down...

So let's be frugal with resources, and delete resources when we don't need them anymore:


In [115]:
predictor.delete_endpoint(delete_endpoint_config=True)

Gracefully stopping... (press Ctrl+C again to force)


## (Optional) Automatic Hyperparameter Optimization - HPO

Rather than manually tweak parameters to tune the model performance, we can get SageMaker to help us out.

We'll simply tell SageMaker:

- The type and allowable range of each parameter,
- The metric we want to optimize for, and
- Strategy and resource constraints

...and the service will set up jobs for us to find the best combination.


### (Hyper-)Parameter Definitions


In [ ]:
from sagemaker.tuner import CategoricalParameter, ContinuousParameter, HyperparameterTuner, IntegerParameter

hyperparameter_ranges = {
    "epochs": IntegerParameter(2, 7),
    "learning_rate": ContinuousParameter(0.01, 0.2),
}


### Objective Metric

'Metrics' in SageMaker are scraped from the console output of jobs, by way of regular expressions.

We can define multiple metrics to monitor, but HPO requires us to specify that exactly one of them is the **objective** metric to optimize:


In [ ]:
metric_definitions = [{ "Name": "loss", "Regex": "loss: ([0-9\\.]+)" }]
objective_metric_name = "loss"
objective_type = "Minimize"


### Start the Tuning Job

We already defined our Estimator above, so we'll just re-use the configuration with minor adjustments.

Note that the Estimator's `hyperparameters` will be used as base values, and overridden by the HyperParameterTuner where appropriate.


In [ ]:
# Keep per-job resources modest, so that parallel jobs don't hit any limits:
estimator.instance_type = "ml.c5.xlarge"
estimator.instance_count = 1

In [ ]:
tuner = HyperparameterTuner(
    estimator,
    objective_metric_name,
    hyperparameter_ranges,
    metric_definitions,
    base_tuning_job_name="news-hpo-pytorch",
    max_jobs=6,
    max_parallel_jobs=2,
    objective_type=objective_type
)

tuner.fit(inputs)


### Check On Progress

HPO jobs can take a long time to complete, and can run multiple training jobs in parallel - each on multiple instances... Which is why the `fit()` call above doesn't wait by default, and won't show us a potentially-confusing consolidated log stream.

Go to the Training > Hyperparameter Tuning Jobs page of the [**SageMaker Console**](https://console.aws.amazon.com/sagemaker/home#/hyper-tuning-jobs) and select the job from the list.

You can see all the training jobs triggered for the HPO run, as well as overall summary metrics.

This information can be accessed via the API/SDKs too of course. For example we can wait for HPO to finish like the below:


In [ ]:
import boto3
import time

# Wait until HPO is finished
hpo_state = None
smclient = boto3.Session().client("sagemaker")

while hpo_state is None or hpo_state == "InProgress":
    if hpo_state is not None:
        print("-", end="")
        time.sleep(60)  # Poll once every 1 min
    hpo_state = smclient.describe_hyper_parameter_tuning_job(
        HyperParameterTuningJobName=tuner.latest_tuning_job.job_name
    )["HyperParameterTuningJobStatus"]

print("\nHPO state:", hpo_state)


### Using the Model

Just like with our `estimator`, we can call `tuner.deploy()` to create an endpoint and `predictor` from the best-performing model found in the HPO run.


## Review

In this notebook, we refactored our local code to train and deploy the same Keras model using SageMaker.

The benefits of this approach are:

- We can automatically provision specialist computing resources (e.g. high-performance, or GPU-accelerated instances) for **only** the duration of the training job: Getting good performance in training, without leaving resources sitting around under-utilized
- Our trained model can be deployed to a secure, production-ready web endpoint with just one SDK call: No container or web application packaging required, unless we want to customize the behaviour
